FROM nvcr.io/nvidia/pytorch:22.07-py3

WORKDIR /

COPY requirements.txt ./

RUN python -m pip install --upgrade pip
RUN pip install wheel && \
    pip install -r requirements.txt && \
    pip install gradio

COPY scripts/generate/alpaca_load.py /

RUN python alpaca_load.py

COPY scripts/generate/alpaca.py /


CMD ["python", "alpaca.py"]
