FROM nvcr.io/nvidia/pytorch:22.07-py3

WORKDIR /

COPY requirements.txt ./

RUN python -m pip install --upgrade pip
RUN pip install wheel && \
    pip install -r requirements.txt && \
    pip install gradio

COPY scripts/generate/alpaca_load.py /

RUN python alpaca_load.py

COPY scripts/prompts/prompt_generator.py /
COPY data/generated/samples.json /


CMD ["python", "prompt_generator.py", '--samples', 'samples.json']
