name: flake8 Lint

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: install docstring
        run: pip install flake8 mccabe flake8-docstrings
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          args: --max-complexity 20 --flake8-docstrings numpy
          max-line-length: "120"
          exclude: \"__init__.py demos/* .ipynb_checkpoints/* \" 
          ignore: F401
